Combine sdk and cli
subspace/pulsar pull request #290
Opened 2024-01-23 11:18 UTC by ParthDesai

# Description
This PR combines [subspace-sdk](https://github.com/subspace/subspace-sdk) into this repository. 

## What is changed?

### First commit
First commit combines sdk and cli and some changes to make it compile and test successfully. The integration test and examples of sdk shifted to the root of the project so that they can be recognized by the rust ecosystem.

### Second commit
Second commit updates the test CI. The pulsar CI was running format, test and clippy in one job but due to addition of sdk tests which are long running, we need to have different jobs.

2024-01-23 11:30 UTC, nazar-pc requested changes
I understand that this is a straightforward conversion, but this is not how it should generally be done. First, the repository should be converted into workspace, with `pulsar` being not the root package, but rather one of workspace packages instead. Then SDK should be added as another workspace member that Pulsar can use, that way you have one lock file and don't need such a messy CI and `cd sdk` in strategic places.

2024-01-23 11:30 UTC, nazar-pc commented on clippy.toml
> +disallowed-types = ["std::sync::Mutex", "std::sync::RwLock", "std::sync::Once", "std::sync::Condvar"]
Honestly it doesn't make a lot of sense to me. There is nothing wrong with these types if they are use properly and clippy will already warn when potentially used incorrectly.

2024-01-23 11:30 UTC, nazar-pc commented on Cargo.toml
> +tracing-subscriber = "0.3"
Examples and integrations tests should be under `sdk`, not main package.

2024-01-23 12:19 UTC, ParthDesai commented
> I understand that this is a straightforward conversion, but this is not how it should generally be done. First, the repository should be converted into workspace, with `pulsar` being not the root package, but rather one of workspace packages instead. Then SDK should be added as another workspace member that Pulsar can use, that way you have one lock file and don't need such a messy CI and `cd sdk` in strategic places.

If we want to go with workspace route, we cannot have sdk as member, since it is itself a workspace and nested workspace is not allowed (yet). In this case, we will need to put members of sdk workspace as part of the root workspace with examples and integration tests in root.

2024-01-23 12:37 UTC, nazar-pc commented
> In this case, we will need to put members of sdk workspace as part of the root workspace

Yes

> with examples and integration tests in root.

As I explained above, we don't need anything at the root. The root should be just a workspace, see how monorepo is organized.

2024-01-23 13:22 UTC, nazar-pc commented
I cancelled extra workflow for now to open CI time for other jobs, the manually triggered workflow is still running

2024-01-25 13:38 UTC, ParthDesai commented
Closing this in favor of https://github.com/subspace/pulsar/pull/291

2024-01-25 13:38 UTC, closed without merging